# Generated by Django 4.2.27 on 2026-01-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='category',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
