# Generated by Django 4.2.27 on 2026-01-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_medicine_category_remove_medicine_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Syrup', 'Syrup'), ('Cream', 'Cream'), ('Injection', 'Injection'), ('Drops', 'Drops')], default='Tablet', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
