# Generated by Django 4.2.27 on 2026-01-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_medicine_medicine_type_alter_medicine_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='description',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='stock',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Syrup', 'Syrup'), ('Cream', 'Cream'), ('Injection', 'Injection')], max_length=20),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
