# Generated by Django 4.2.27 on 2026-01-21 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0005_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('prescription_file', models.FileField(upload_to='prescriptions/')),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Submitted', 'Prescription Submitted'), ('Verified', 'Under Verification'), ('Billed', 'Bill Generated'), ('Delivered', 'Delivered')], default='Submitted', max_length=20)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
