# Generated by Django 4.2.27 on 2026-01-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_prescriptionorder_delete_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionorder',
            name='status',
            field=models.CharField(choices=[('submitted', 'Prescription Submitted'), ('verified', 'Under Verification'), ('billed', 'Bill Generated'), ('delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescriptionorder',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
