# Generated by Django 4.2.27 on 2026-01-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_prescriptionorder_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionorder',
            name='status',
            field=models.CharField(choices=[('submitted', 'Prescription Submitted'), ('verified', 'Under Verification'), ('billed', 'Bill Generated'), ('delivered', 'Delivered')], default='submitted', max_length=20),
        ),
    ]
