# Generated by Django 4.2.27 on 2026-01-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_prescriptionorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionorder',
            name='status',
            field=models.CharField(choices=[('submitted', 'Prescription Submitted'), ('verified', 'Under Verification'), ('billed', 'Bill Generated'), ('paid', 'Payment Completed'), ('delivered', 'Delivered')], default='submitted', max_length=20),
        ),
    ]
