# Generated by Django 4.2.27 on 2026-02-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_prescriptionorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionorder',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
