# Generated by Django 4.2.27 on 2026-02-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_medicine_stock_alter_medicine_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='minimum_stock',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='prescriptionorder',
            name='status',
            field=models.CharField(choices=[('submitted', 'Prescription Submitted'), ('verified', 'verified'), ('billed', 'Bill Generated'), ('paid', 'Payment Completed'), ('delivered', 'Delivered')], default='submitted', max_length=20),
        ),
    ]
