# Generated by Django 4.2.27 on 2026-02-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_medicine_batch_number_medicine_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='image',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='medicine_type',
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('Analgesic', 'Analgesic'), ('Antibiotic', 'Antibiotic'), ('Cardiac', 'Cardiac'), ('Diabetic', 'Diabetic')], default='Analgesic', max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='prescription_required',
            field=models.BooleanField(default=False),
        ),
    ]
