# Generated by Django 4.2.27 on 2026-02-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionorder',
            name='status',
            field=models.CharField(choices=[('submitted', 'Prescription Submitted'), ('verified', 'verified'), ('billed', 'Bill Generated'), ('paid', 'Payment Completed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='submitted', max_length=20),
        ),
    ]
