# Generated by Django 4.2.27 on 2026-03-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_prescriptionorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionorder',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionorder',
            name='status',
            field=models.CharField(choices=[('submitted', 'Prescription Submitted'), ('verified', 'Verified'), ('pickup_only', 'Store Pickup Only'), ('rejected', 'Rejected'), ('billed', 'Bill Generated'), ('cod_selected', 'Cash on Delivery Selected'), ('paid', 'Payment Completed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('out_of_stock', 'Out of Stock')], default='submitted', max_length=20),
        ),
    ]
