# Generated by Django 4.2.27 on 2026-03-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_pharmacistmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacistmessage',
            name='is_read',
        ),
        migrations.AddField(
            model_name='pharmacistmessage',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
