# Generated by Django 4.2.27 on 2026-03-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_remove_pharmacistmessage_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='store_pickup_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('Tablets', 'Tablets'), ('Syrups', 'Syrups'), ('Injections', 'Injections'), ('Medical Devices', 'Medical Devices'), ('Personal Care Products', 'Personal Care Products'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
