# Generated by Django 4.2.27 on 2026-03-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_medicine_store_pickup_only_alter_medicine_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionorder',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionorder',
            name='prescription_file',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
    ]
