# Generated by Django 4.2.27 on 2026-03-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_alter_prescriptionorder_doctor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacistmessage',
            name='is_read_by_user',
            field=models.BooleanField(default=True),
        ),
    ]
