# Generated by Django 4.2.27 on 2026-03-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_pharmacistmessage_is_read_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionorder',
            name='payment_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionorder',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
