# Generated by Django 4.2.27 on 2026-03-13 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_alter_prescriptionorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.medicine'),
        ),
        migrations.AddField(
            model_name='prescriptionorder',
            name='is_stock_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PurchaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('quantity_received', models.IntegerField()),
                ('supplier_name', models.CharField(blank=True, max_length=200, null=True)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.medicine')),
            ],
        ),
    ]
