# Generated by Django 4.2.27 on 2026-03-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_remove_purchaseentry_supplier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacistmessage',
            name='is_read_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
