# Generated by Django 4.2.27 on 2026-04-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_pharmacistmessage_is_read_by_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('Tablets', 'Tablets'), ('Syrups', 'Syrups'), ('Injections', 'Injections'), ('Medical Devices', 'Medical Devices'), ('Personal Care', 'Personal Care'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
